BloomBooks/bloom-harvester

- src/Harvester/HarvestMode.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/HarvestState.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
There are 2 commits, probably easier to review one commit at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/27)
> Better handling of aborted books and better handling of errors from Bloom CLI

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Harvester.cs
I deleted CollectionSettings.HarvesterMode a while back because it didn't look like it was being used... Turns out it is.
Updated major version because the books with this problem are marked succeeded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/28)
> Fix missing narration audio (BL-7655)

- src/Harvester/Harvester.cs
Previously, it would create an issue for every book that was missing the font.
Now, it only creates it for the first book missing that font. (Resets when the Harvester process is restarted)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/30)
> Prevent duplicated missing font YouTrack issues (BL-7673)

- src/Harvester/EnvironmentSetting.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
1) Don't crash if an exception is thrown while reporting to YouTrack. (We want the Harvester to continue running the loop in such a case, not abort the program).
2) Add the Parse Environment setting into the issue report as well for easier diagnostics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/35)
> Harvester Exception handling (BL-7702)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/BookAnalyzerTests.cs
Take this book as an example: https://bloomlibrary.org/browse/detail/vdDvZy7OUL?shelf=Ministerio%20de%20Educaci%C3%B3n%20de%20Guatemala
It has 2 instances of bloom-content1 which say lang="quc", but tons of bloom-content1 instances which say lang="es".
The old code picks "quc" for it, and then some of the publishing code crashes at the mixup in what the right language1/title should be.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/34)
> Fix bug if book contains inconsistent lang tags (BL-7707)

- src/Harvester/BookAnalyzer.cs
I don't see any other settings that can be usefully obtained from the
meta.json file.  There may be other settings that can affect the output,
especially for multilingual books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/44)
> Fix to use proper page numbering style (BL-7781)

- src/Harvester/HarvestStateBatchUpdater.cs
- src/Harvester/HarvestStateUpdater.cs
- src/Harvester/Program.cs
Associated with: https://issues.bloomlibrary.org/youtrack/issue/BL-7909
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/49)
> Add ability to batch set Parse objects to a specific state (for BL-7909)

- src/Harvester/HarvestStateBatchUpdater.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
Otherwise, it needs to be recompiled and re-built to change the value. If you wanted to change its value on a machine running the Harvester (and it downloads the binaries), this would be a big nuisance for a small thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/51)
> Make delayAfterEmptyRunSecs configurable

- src/Harvester/HarvestStateBatchUpdater.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/ProcessedFilesInfoGenerator.cs
We seem to be getting intermittent errors from the Parse client. Hopefully this will prevent that from generating spurious issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/45)
> Add more null checks (BH-35)

- build/downloadAndExtractZip.ps1
- build/getDependencies.ps1
- build/removeFileSystemItemSynchronous.ps1
- src/Harvester/BloomHarvester.csproj
This is Part 1 of 3. In this Part, I want the build in TeamCity to take charge of copying dependencies it needs into its build output folder.   (This will also help make sure some DLL's required are runtime don't go un-copied)
Part 2: Update TeamCity to have the Harvester build publish its entire build output folder, including the dependencies from Bloom. The reason why i want this to happen is so that the dependencies from Bloom are a snapshot of a specific version from Bloom, rather than what we have now where the Bloom dependencies are auto-updated to the latest build of Bloom. But the Harvester binaries are not necessarily rebuilt every day, so the dependencies could get out of sync. I think it's better to lock it to a specific version.
Part 3: Modify the updateDeployment script to …
> Build will copy dependencies to the build output folder (BL-80902)

- src/HarvesterTests/BloomHarvesterTests.csproj
No longer requires the machine running the test to just happen to have the appropriate DLL already installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/72)
> Add missing dependency required by libtidy

- src/Harvester/EnvironmentSetting.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This PR makes it more likely that two Harvesters can run side-by-side on the same user account on a machine.
However, for our actual Harvester instances, I'm converting them to run on separate user accounts on the same machine instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/77)
> Decrease likelihood of error if multiple Harvesters running

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
Previously, textOverPicture boxes were being excluded from the word count. Now they are included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/83)
> Calculate computedLevel properly on pure comic books

- src/Harvester/Program.cs
At the moment, phash computation results can differ between Windows and
Linux.  This would have to be dealt with somehow before we could run
Harvester on a Linux machine instead of a Windows machine.
(This is currently moot because Harvester won't even build on Linux, but
this change should give pause to moving in that direction.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/94)
> Prevent Harvester from trying to run on Linux (BL-8475)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Program.cs
It isn't needed and is never used.  And Bloom has moved on to Geckofx60.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/99)
> Remove the reference to Geckofx45 from harvester

- src/Harvester/Harvester.cs
If the environment variable is not set, or has an invalid value, the
user's local application folder is used.  If that somehow fails, the
user's temp folder is used as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/112)
> Allow setting cache root folder in environment variable (BL-8642)

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
Comic books won't produce ePUB files, but will produce all of the other
artifacts okay.  Bloom has already been fixed to not crash trying to
create ePUBs for comic books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/116)
> Allow ePUBs to fail without making the entire harvest fail

- build/copyBloomDependencies.sh
It may not be quite bulletproof, but it works a lot better for my normal
usage.  It works in the git-bash shell, but fails in the cygwin shell
because of the CRLF line endings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/117)
> Simplify and bulletproof build/copyBloomDependencies.sh (20200722)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/119)
> Fix UpdatePerceptualCrash crashing when Bloom renames folder (BH-5551)

- src/Harvester/BloomHarvester.csproj
BloomDesktop recently upgraded its dependencies, so Harvester does too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/121)
> Upgrade packages to match BloomDesktop

- src/Harvester/AlertManager.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/AlertManagerTests.cs
This sidesteps the current limit of 5 error reports per day maximum.
There is now a limit of 1 report per new/updated book per day, and
5 reports per uploader of new/updated books per day, so there is still
some limits on bug reports per day, but not as strict for new (and
updated) books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)
> Create Harvester youtrack issues for New or Updated Books (BL-8919)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/162)
> Fix a null object crash in finding bookshelf (BH-6078 and BH-6083)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
Also add Mono.Unix reference that is now needed by SIL.Core (or one of
the other libraries used by Bloom?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/178)
> Update SIL.Core to match what Bloom uses (20220802)

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
* harvester will now use the "language-display-names" in
meta.json for SL custom names too
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/187)
> BL-11754 Update Harvester to use SL custom names

- src/Harvester/BookAnalyzer.cs
This also handles getting books with the new (temporary?) layout of images in 6.2 that always have a placeHolder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/215)
> Avoid taking phash of placeHolder.png for harvested book (20250324)
