- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Parse/ParseException.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/Properties/launchSettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/5)
> Allow command line to specify WHERE filter (BL-7241)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Parse/BatchableOperation.cs
- src/Harvester/Parse/UpdateOperation.cs
- src/Harvester/Properties/launchSettings.json
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/7)
> Switch .csproj format to the new project format

- build/getDependencies-windows.sh
- src/Harvester/BloomHarvester.csproj
- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Parse/UpdateOperation.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/8)
> Download books from AWS (BL-7249)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/Harvester/WebLibraryIntegration/S3UrlComponents.cs
- src/HarvesterTests/HarvesterTests.cs
- src/HarvesterTests/WebLibraryIntegration/S3UrlComponentsTests.cs
Depends on https://github.com/BloomBooks/BloomDesktop/pull/3275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/9)
> Upload books to new AWS S3 bucket (BL-7249)

- README.md
- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/10)
> Upload bloomd files

- README.md
- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/11)
> BL-7361 Publish epub

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/13)
> BL-7345 harvested books should use uploaded brandings

- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/14)
> ReadOnly option allows download only

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/15)
> Mark harvester created .bloomd files as such (BL-7409)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/16)
> Harvester must pass the enterprise flag when creating BloomDs (BL-7500)

- README.md
- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Parse/ParseException.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/17)
> Run bloomd/epub creation code in separate process (BL-7547)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/18)
> Fix more epub deadlocks (BL-7547)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/19)
> Remove unnecessary dependency on Bloom (BL-7547)

- README.md
- build/copyBloomDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/21)
> Add script to copy dependencies from Bloom

- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/20)
> Report Error if Harvester is missing fonts (BL-7566)

- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/BaseLogEntry.cs
- src/Harvester/LogEntries/LogLevel.cs
- src/Harvester/LogEntries/MissingBaseUrlWarning.cs
- src/Harvester/LogEntries/MissingFontError.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Parse/Model/HarvestState.cs
- src/Harvester/Parse/Model/ParseObject.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
- src/HarvesterTests/LogEntries/BaseLogEntryTests.cs
- src/HarvesterTests/LogEntries/MissingFontErrorTests.cs
- src/HarvesterTests/Parse/ParseClientTests.cs
Skips re-processing a book with missing fonts until the font is installed or the book is re-updated by the author.
(This will cause fewer YouTrack issues to be created)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/22)
> Skips re-processing books if we're still missing fonts (BL-7566)

- build/copyBloomDependencies.sh
- src/Harvester/BloomHarvester.csproj
- src/Harvester/HarvestMode.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/BookUpdateOperation.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Parse/Model/Date.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Parse/UpdateOperation.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/HarvesterTests/HarvesterTests.cs
- src/HarvesterTests/Parse/ParseClientTests.cs
- src/HarvesterTests/Parse/UpdateOperationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/24)
> Check Harvester versions when processing in Default mode (BL-7498)

- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/25)
> Harvester - Enable Run Continually (BL-7651)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/29)
> Added comments describing alternate solution

- src/Harvester/Logger/AzureMonitorLogger.cs
- src/Harvester/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/31)
> Print Azure logs to console as well

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/32)
> Don't report empty string as a missing font

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/33)
> Add book.objectId to the issue reported to YouTrack

- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/36)
> Get the correct language 2 and language 2 settings for monolingual books (BL-7716)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/38)
> Preserve language display names (BL-7693)

- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/40)
> Add options to skip uploading certain artifacts

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Program.cs
- src/HarvesterTests/BookAnalyzerTests.cs
- src/HarvesterTests/Parse/Model/BookTests.cs
- src/HarvesterTests/Parse/ParseClientTests.cs
The framework is in place for pdfs and Bloom Reader books as well, but
those are currently assumed to be okay from harvester's perspective.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/39)
> Guess whether epubs are likely to be suitable (BL-7677)

- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/41)
> Send all Harvester exceptions to BH now instead of some to BL (BL-7752)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/42)
> Simplify heuristic for determining epub suitability (BL-7677)

- src/Harvester/HarvestStateUpdater.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Parse/Model/Language.cs
- src/Harvester/Parse/Model/User.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/ProcessedFilesInfoGenerator.cs
- src/Harvester/Program.cs
- src/Harvester/Properties/launchSettings.json
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/43)
> Generate processed files TSVs

- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/46)
> Fix hangs if Bloom subprocess crashes

- README.md
- build/getDependencies-windows.sh
- src/Harvester/BloomHarvester.csproj
Now it sucks in all the dependencies from Bloom. And I use a PostBuild step to copy all of that into the build directory.
The DLL/etc. side of things should be fixed, but still need to figure out what to do about the javascript output and the localizations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/47)
> Update Harvester dependencies (BL-7909) to require less box setup

- src/Harvester/HarvestStateBatchUpdater.cs
- src/Harvester/Program.cs
- src/HarvesterTests/Parse/Model/BookTests.cs
- src/HarvesterTests/Parse/ParseClientTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/50)
> HarvestStateBatchUpdater: Add a dry-run option. Also fix failing unit tests

- src/Harvester/Logger/AzureMonitorLogger.cs
- src/Harvester/Logger/FileLogger.cs
- src/Harvester/Logger/NullLogger.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/52)
> Add file logging (makes Harvester box debugging easier) (BL-7909)

- src/Monitoring/MonitoringReadme.txt
- src/Monitoring/settings.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/53)
> Checkin settings for monitoring application

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/54)
> Fix bug causing getFonts to timeout (for BL-8061)

- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/BaseLogEntry.cs
- src/Harvester/LogEntries/GetFontsError.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/55)
> Require getMissingFonts() to succeed in order to process book (BL-8065)

- src/Harvester/Parse/ParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/56)
> More robust handling of JSON parsing exceptions (BH-5282)

- src/Harvester/AlertManager.cs
- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/AlertManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/57)
> Automatic silencing if alerts too noisy (BL-8062)

- build/updateDeployment.ps1
Also:
* Checks if Bloom subprocess is running.
* Synchronous delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/60)
> Auto-update now expects BH build to contain all dependencies (BL-8092)

- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/61)
> Harvester auto-updates thumbnails (BL-8054)

- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/Book.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/Parse/Model/BookTests.cs
I added a link to the BloomLibrary detail page for the book for each of these, because I need it a lot.
I also made it consistently print out certain diagnostic info.
I added a command line option that can be turned on to disable reporting to YouTrack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/62)
> Error Reporting: Add BL link, consistent formatting, add suppressErrors

- src/Harvester/Logger/AzureMonitorLogger.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/64)
> Clearer error reporting if instrumentation key is null (BH-5376)

- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/BaseLogEntry.cs
- src/Harvester/LogEntries/MissingBloomDigitalIndexError.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/65)
> Add error if index.htm file is missing

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/66)
> Add exit code descriptions to YouTrack issue

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/67)
> Check for index.htm in the correct directory

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/Logger/ConsoleLogger.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Program.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
- src/HarvesterTests/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/71)
> Calculate the Perceptual Hash of books (BL-8234)

- build/updateDeployment.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/73)
> Parameterize updateDeployment script to handle dev or prod

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/BookTests.cs
- src/HarvesterTests/HarvesterTests.cs
- src/HarvesterTests/Parse/Model/BookModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/74)
> Better error reporting in case of error in ShouldProcessBook()

- src/Harvester/BloomHarvester.csproj
- src/Harvester/Parse/Model/BookModel.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/75)
> Fix null reference exception

- src/Harvester/Book.cs
- src/HarvesterTests/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/76)
> Remove line endings from perceptual hash (BL-8327)

- build/updateDeployment.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/78)
> Change updateDeployment script for running under multiple user accounts

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/IO/FileIO.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/79)
> Updating PHash only no longer deletes other artifacts

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/80)
> Check for cases where pHash returns 0x00...000

- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
Previously, the logger was referenced before the logger was initiailzed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/81)
> Fix Logger exception

- src/Harvester/Parse/ParseClient.cs
- src/HarvesterTests/Parse/Model/WriteableParseObjectTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/82)
> Fix bug where old value of pHash was not being read, causing wrong diff

- src/Harvester/BloomHarvester.csproj
- src/Harvester/FontChecker.cs
- src/Harvester/HarvestStateBatchUpdater.cs
- src/Harvester/Harvester.cs
- src/Harvester/Logger/NullLogger.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/ProcessedFilesInfoGenerator.cs
- src/HarvesterTests/FontCheckerTests.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/86)
> Add support for books specifying font-families (BH-5426)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
- src/HarvesterTests/WebLibraryIntegration/YouTrackIssueConnectorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/88)
> Update YouTrack submission to use Bloom code directly (20200504)

- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/90)
> Set S3 Cache-Control headers on upload (BL-8198)

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/89)
> Set artifact suitability to false when unsuccessful (BL-8413)

- src/Harvester/Harvester.cs
- src/Harvester/Logger/StringListLogger.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/91)
> Prevent creating issue if book deleted while processing (BL-8388)

- src/Harvester/Parse/ParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/92)
> Increase parse query limit from 1000 to 10000 (BL-8445)

- src/Harvester/Harvester.cs
- src/Harvester/IO/DiskSpaceManager.cs
- src/Harvester/IO/DriveInfo.cs
- src/Harvester/Logger/AzureMonitorLogger.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/S3UrlComponents.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/BookTests.cs
- src/HarvesterTests/HarvesterTests.cs
- src/HarvesterTests/IO/DiskSpaceManagerTests.cs
- src/HarvesterTests/Parse/Model/BookModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/87)
> Cache book downloads (BL-8387)

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/93)
> Improve the query where optimizations based on mode (BL-8446)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/96)
> Fix "Failure to load visibility document" harvesting old books (BL-8485)

- src/Harvester/Harvester.cs
The previous constraint was too strict, leaving out books we want to
process by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/97)
> Relax Default query optimization (BL-8446)

- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/98)
> Fix test to reflect new reality (BL-8485)

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/IO/FileIO.cs
- src/HarvesterTests/BookTests.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/95)
> Set show field for social media sharing available (BL-8406)

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This code merely lets Bloom use its existing method for isolating the
proper HTML file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/100)
> Handle two HTML files found in a book's folder (BL-8508)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/101)
> Fix unused variable

- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/HarvestState.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/102)
> Add FailedIndefinitely state to Harvester (BL-8448)

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/IO/FileIO.cs
- src/HarvesterTests/BookTests.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/104)
> Harvester processes all it can with missing fonts (BL-8449)

- build/getDependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/105)
> getDependencies script works even if directory is empty

- build/getDependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/106)
> Add GraphicsMagick folder to Bloom download in getDependencies.ps1

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
We need unique folder names for reliable caching, so use the book id
strings for the cache folders while still using the book title as the
basis of the collection subfolders.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/108)
> Separate concept of cache folder from collection book folder (BL-8628)

- build/getDependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/110)
> Fix build script to pull in Bloom's app.config

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/109)
> Don't show (uncreated) artifacts if any fonts are missing (BL-8342)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/LogType.cs
- src/HarvesterTests/BookAnalyzerTests.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/111)
> Show why artifact approval failed in harvestLog (BL-8431)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This uses the CoenM.ImageSharp.ImageHash library which seems to work well
for our needs and which is MIT licensed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/107)
> Implement perceptual hashing inside harvester (BL-8607)

- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/LogType.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/113)
> Report a HarvesterLog entry when phash calculation fails.

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/115)
> Fix bug where settings are incorrect after first book w/missing font.

- src/Harvester/Book.cs
- src/Harvester/Parse/Model/BookModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/118)
> Add BrandingProjectName to BookModel properties (BL-8790)

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
Depends on this BloomDesktop PR: https://github.com/BloomBooks/BloomDesktop/pull/4046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/120)
> Preserve xmatter settings from book. (BL-9084)

- src/Harvester/BloomHarvester.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/122)
> Bump major version to re-run with preserve branding fix (BL-9084)

- src/Harvester/FontChecker.cs
- src/HarvesterTests/FontCheckerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/123)
> Add 宋体 (Song Ti) and others to list of generic font fallbacks.

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/124)
> Get the collection sign language from meta.json (BL-9305)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
Makes it match the DLL's used by updated version of BloomDesktop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/125)
> Use updated libpalaso libraries

- src/Harvester/BloomHarvester.csproj
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
Having the version match the BloomDesktop version seems to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/126)
> Fix L10nSharp problem with Palaso.xlf

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/127)
> Update version numbers again to match BloomDesktop

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/128)
> Increase timeout (BH-5962)

- src/Harvester/HarvestMode.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/HarvestState.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)
> Add HarvestState.Requested to the possible states (BL-8287)

- src/Harvester/HarvestMode.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/HarvestState.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/130)
> Merge from master to release 20210217

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/132)
> Download books when harvest is requested by users (BL-9719)

- src/Harvester/AlertManager.cs
- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/AlertManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/133)
> Merge harvester master to release 20210323

- src/Harvester/Logger/AzureMonitorLogger.cs
- src/Harvester/Logger/FileLogger.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/134)
> Enhance local file logging to be more useful for harvest manager

- src/Harvester/Logger/AzureMonitorLogger.cs
- src/Harvester/Logger/FileLogger.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/135)
> Merge from master to release 20210407

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/136)
> Remove unused packages and update others to match Bloom (20210421)

- src/Harvester/AlertManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/137)
> Remove possible null object problem (BH-5745)

- src/Harvester/AlertManager.cs
- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/138)
> Merge master to release 20210519

- src/Harvester/Harvester.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/WebLibraryIntegration/HarvesterBookTransfer.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/139)
> Fix BloomHarvester for recent changes in BloomDesktop (BL-10182)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/143)
> Fix an error report in Harvester to make problem clearer (20210723)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/144)
> Bring Harvester up to date with Desktop packages (BL-10254)

- src/Harvester/BloomHarvester.csproj
- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/145)
> Merge master to release - 20210817 (for BL-10254)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/146)
> Add DefaultBookTags with bookshelf tag to created collection settings

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/148)
> Merge from master 20211101

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/149)
> Fix a crash computing perceptual hash values (BH-5984)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/150)
> Merge from master 21011214

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)
> Handle longer filenames inside book folders (BH-5988)

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/153)
> Merge from master to release 20211215

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)
> Enable Harvester to create .bloom files (BL-10673)

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/154)
> Merge master to release 20220104

- src/Harvester/BookAnalyzer.cs
I tend to think the C# behavior is wrong, but we have to deal with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/155)
> Fix crash when Exif orientation not stored as unsigned int (BH-6025)

- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/156)
> Check for books without PDF files and flag them (BL-10816)

- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/158)
> Fix unit tests broken from removing title sanitizing (BL-10406)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/159)
> Merge master to release - 20220107

- src/Harvester/WebLibraryIntegration/HarvesterBookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/160)
> Improve message for missing meta.json file (BL-10540)

- src/Harvester/WebLibraryIntegration/HarvesterBookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/161)
> Merge from master to release 20220119

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/HarvesterTests/Parse/Model/BookModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/164)
> Update bookshelf: tag to current user choice for book (BL-10031)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/HarvesterTests/Parse/Model/BookModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/165)
> Merge master to release 20220302

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/166)
> Improve reporting of missing files in Bloom Harvester (BH-6100)

- src/Harvester/FontChecker.cs
- src/Harvester/Harvester.cs
- src/Harvester/LogEntries/LogType.cs
- src/Harvester/WebLibraryIntegration/YouTrackIssueConnector.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/167)
> Catch ttc files when checking fonts in harvester (BH-6107)

- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/170)
> Fix a couple of failing harvester unit tests (20220314)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/173)
> merge master to release for BL-11050 fix

- src/Harvester/Book.cs
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/Program.cs
Also sets new parse books field bloomPUBVersion to 1 when .bloompub
upload succeeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/168)
> Change harvester to use .bloompub instead of .bloomd (BL-10720)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/174)
> Update SIL.Core version to match BloomDesktop master branch (20220613)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/175)
> Merge master into release 20220613

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/177)
> Upgrade libpalaso version to 10.0.0-beta0063

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/179)
> Merge from master to release 20220802

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/181)
> Ignore elements with box-header-off when determining epub suitability (BL-11523)

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/182)
> Improve comments after code review (BL-11523)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/183)
> Always allow publishing "fixed" mode ePUBs in harvester (BL-11424)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloom-harvester/184)
> Fix old uploads to use flowable mode for epub generation (BL-11424)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/188)
> Update packages to keep up with BloomDesktop (20230112)

- src/Harvester/BloomHarvester.csproj
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/189)
> Merge to release for updated packages 20230112

- src/Harvester/BloomHarvester.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/190)
> Finish updating harvester for Bloom and SIL.Core package updates

- build/getDependencies.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/191)
> Update getDependencies.ps1 to use harvester tag instead of latest

- src/Harvester/FontChecker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/192)
> Fix harvester to know about Bloom font serving (20230510)

- src/Harvester/Book.cs
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/194)
> Set epub and pdf artifact langTags (BL-12326)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)
> Add language location to generated bloomCollection file (BL-12583)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)
> Use the uploaded collection settings file if available (BL-12583)

- .gitignore
- BloomHarvester.sln
- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BloomHarvesterTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/197)
> Merge master to release 20230808

- src/Harvester/FontChecker.cs
* one book had 'AndikaNewBasic-Regular' in a style
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/198)
> BL-12662 Handle odd font form

- src/Harvester/BookAnalyzer.cs
- src/HarvesterTests/BookAnalyzerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/199)
> Improve BookAnalyzer getting collection language settings (BL-12703)

- src/Harvester/FontAnalytics.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/200)
> Simplify parse queries

- src/Harvester/Parse/ParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/201)
> Further simplify parse queries

- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/BloomParseClient.cs
- src/Harvester/Parse/ParseClient.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
Bloom changes must merge first. Also has various changes to get harvester working with Bloom 5.7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/202)
> Make BookAnalyzer a subclass of CollectionSettingsRecreator (BL-13050)

- src/Harvester/Parse/BloomParseClient.cs
- src/Harvester/Parse/ParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/203)
> Conform to latest BloomDesktop changes

- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/204)
> Write harvester log properly after exception caught (20240826)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/205)
> Use SafeXmlElement in BookAnalyzer

- build/copyBloomDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/207)
> Fix copy Bloom script to handle Distfiles content better (20241104)

- src/Harvester/FontBackup.cs
- src/Harvester/Program.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/206)
> Add "backupFonts" command to Bloom Harvester (BL-10035)

- src/Harvester/FontChecker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/208)
> Update font checking for changes to Bloom's FontFileFInder (20241118)

- src/Harvester/FontChecker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/209)
> Don't check validity of missing fonts

- src/Harvester/Book.cs
- src/Harvester/Harvester.cs
- src/Harvester/Program.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/210)
> Upload jsonText artifacts

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/211)
> Handle derivatives made with old Blooms of new books (BL-14127)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/212)
> Ignore uploaded collection settings if upload version < 5.5 (BL-14127)

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/214)
> Merge from master to release 20250312

- src/Harvester/BookAnalyzer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/216)
> Handle bloom-canvas in looking for image to phash

- src/Harvester/Book.cs
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/HarvesterTests/BookAnalyzerTests.cs
- src/HarvesterTests/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/217)
> Make branding survive harvesting (BL-14379)

- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/221)
> Fix unit test for new BookHashFromImages field (BL-14980)

- scripts/HARVESTER-CLEANUP.md
- scripts/cleanupDev.sh
- scripts/cleanupProduction.sh
- src/Harvester/BookAnalyzer.cs
- src/Harvester/BookHashUpdater.cs
- src/Harvester/Harvester.cs
- src/Harvester/Parse/Model/BookModel.cs
- src/Harvester/Program.cs
- src/HarvesterTests/BookAnalyzerTests.cs
- src/HarvesterTests/HarvesterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/222)
> Merge from master to release 20250724

- src/Harvester/BookHashUpdater.cs
- src/Harvester/WebLibraryIntegration/HarvesterS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/223)
> Fix some problems with downloading for updating hashes (BL-14980)

- src/Harvester/Harvester.cs
This allows handling invalid/illegal fonts as well as missing fonts. The new code in BloomDesktop is also more accurate with regard to which fonts are actually used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/225)
> Handle font errors detected during CreateArtifacts (BL-15003)

- src/Harvester/Book.cs
- src/Harvester/BookAnalyzer.cs
- src/Harvester/Harvester.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/bloom-harvester/229)
> Merge from master 20251006
